services:
  text-legend:
    image: ghcr.io/e5sub/text-legend:latest
    container_name: text-legend
    hostname: text-legend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Shanghai
      - PORT=3000
      - DB_CLIENT=sqlite
      - DB_FILENAME=/app/data/game.sqlite
      - DB_POOL_MAX=1
      - SQLITE_WAL=true
      - SQLITE_SYNCHRONOUS=NORMAL
      - SESSION_TTL_MIN=0
      - ADMIN_BOOTSTRAP_SECRET=change_me
      - ADMIN_BOOTSTRAP_USER=admin_account
    volumes:
      - ./data:/app/data
